### ISSUE TITLE
I couldn't find a way to contact you

### ISSUE THREAD

**Issue by CubeMakesGames** [mikeee324/OpenPutt#20]
Hey Mikeee324, I think this is a really cool project and I'd love to get involved and help you achieve the goal of making Golf world's much easier to make for VRChat, I played the Junkyard Minigolf yesterday and it was the best golf world I've played yet and I started thinking about trying to make a golf world of my own and then I looked into it and found this GitHub and thought maybe you'd like some help from someone just as passionate about golf in VRChat to help you whether it be with modelling, Coding or whatever else is needed

I also have tons of free time

I know this is probably a long shot but I hope to hear back from you, regardless I'm rooting for you - Cube

**Comment by mikeee324** [comment]
Hiya, apologies for the late reply!  
I'm glad you love the project. If you'd like to help out I'd definitely appreciate it!  
I don't have tonnes of stuff left to add to the main library as it is right now. The bulk of the recent work I've done is optimising various parts to reduce frame stutters and trying to track down weird issues.  
  
If you'd like to you can add me on discord with the same name (but lowercase) and we can figure things out a bit better!

**Comment by CubeMakesGames** [comment]
I think I added you but in case I didn't my discord name is formingcube2

**Comment by mikeee324** [comment]
Yep, received it :)
I'll close this issue down for now!
