### ISSUE TITLE
Desktop Mode

### ISSUE THREAD

**Issue by mikeee324** [mikeee324/OpenPutt#4]
Needs a lot of thinking about..  
  
Ideally we have some kind of fancy camera thing and a way of setting direction and velocity.  
I want to do this eventually but you can still kinda play it already..

**Comment by CubeMakesGames** [comment]
The fancy camera sounds like a good idea the only problem would be how to implement it in a way that allows it to be super intuitive/easy to use

**Comment by mikeee324** [comment]
Yeah the biggest thing is thinking about how to make things like this generic enough that it'll look and work alright in any world we drop OpenPutt into.

**Comment by mikeee324** [comment]
First draft of a desktop mode was added in commit f56757aa7d7974ce884f025f6fb546bf95838b46  
Still some bits left to mess with, but works for the most part. 

https://github.com/mikeee324/OpenPutt/assets/4761751/3ceedd83-3bb1-4a30-9980-22546c9591a2

**Comment by mikeee324** [comment]
Closing this as it is working now!
