### ISSUE TITLE
Ball looses momentum way too fast

### ISSUE THREAD

**Issue by Greendayle** [mikeee324/OpenPutt#5]
Tried the Junkyard Golf world. I love the idea of your prefab and most likely will make a map using it one day. But, I've found a big issue - ball seems to act more like a ping pong ball than a golf ball. Compared to PuttPutt and Walkabout Minigolf in your map golf ball just doesn't want to roll at all. The problem might be also exaggerated by the fact that Junkyard Golf courses are GIANT, they are definitely bigger than any other courses I've seen, but I had trouble getting the ball across them even with 1.5 power scaling.

I didn't really look at the prefab in unity yet, so I'll ask here, is there an easy way to increase ball momentum?

**Comment by mikeee324** [comment]
There is a couple of options related to scaling the power on hits on the ball. Though most of the problem you describe with it losing momentum will be related to the rigidbody on the ball and the friction on the ground etc. All of which you should be able to tweak fairly easily. 

Getting these numbers right has been a pain as I'm just learning things as I go with Unity etc. I more or less got it to a point where people stopped really complaining and moved on with the rest of the system.

If you manage to have a play with the prefab and can make it feel nicer, let me know!

**Comment by mikeee324** [comment]
I'll be closing this as it is a thing that can be adjusted for each world using the Physics Materials etc n the prefab.  
I think my test world has a nicer setup now after tweaking them in there and the settings there should also be the prefab defaults.
