### ISSUE TITLE
Missing Prefab with Guid on "HoleStartPad."

### ISSUE THREAD

**Issue by Sornos** [mikeee324/OpenPutt#66]
Hi,

I'm still learning how to use Unity, so it is possible it is an error on my part.  I've been playing minigolf with a few friends (with Junkyard usually being the warmup course. :) ) and was wanting to make some new courses; partially inspired by real life minigolf a decade ago.

Anyway, I've been going through the "Getting Started" and slowly working my way through the instructions.  Everything makes sense, but when I "Add New Course" it spawns the hole cube and the starting pad, but the pad lacks any textures.  I can align it with the course but when I try to run it all I can do is drop a ball on it.  Pressing the key to get into golf mode causes it to briefly go to it and immediately kicks back to normal avatar view.  Whenever I view the HoleStartPad with the hierarchy it mentions "Missing Prefab with Guid" followed by a long hexadecimal string.  I've created a few other projects to see if it remains consistent and it does.

Again, it's possible I do not know what I am doing, but wanted to submit just in case it is a bug.  Thanks for reading.

![Screenshot 2024-12-06 161602](https://github.com/user-attachments/assets/d6996c56-4900-401f-92d1-cc5d34f41099)

**Comment by mikeee324** [comment]
Hmmm, I'll have a look into it and see if I can figure out what's happened with it!

**Comment by mikeee324** [comment]
I'm not able to replicate this myself even on fresh projects. I wonder if you're somehow missing the fbx file for the start pad itself.  
Can you check to see if it's in this folder below?  
![image](https://github.com/user-attachments/assets/7e5587fc-4bc1-4036-a372-e1a2c0141074)

**Comment by Sornos** [comment]
Hello Mike,

When I look in that folder, I see the following files:

HoleEnter.mp3
HoleStartPad.blend
HoleStartPad.blend1
HoleStartPad.mat

I'm not seeing any files that have a fbx extension.  If the files are correct, I might try it on a different PC.

Edit: I don't see any icons that show a box.

**Comment by mikeee324** [comment]
Oh, apologies there's no fbx, the blend file is the file that it should be using.  
If you don't see a box what icon does the .blend file have?  
  
It sounds like your unity install doesn't know how to import blender files for some reason. I can probably work around it by exporting everything to fbx like I probably should have done already hah  
  
When I get chance I'll do that and push an update out

**Comment by mikeee324** [comment]
Also, going to this:  

> Pressing the key to get into golf mode causes it to briefly go to it and immediately kicks back to normal avatar view. 
  
Do you see any error messages pop up in the console tab in unity when this happens?

**Comment by mikeee324** [comment]
Just pushed 0.8.5 out. Hopefully that fixes the prefab problem for you, please let me know how it goes :)

**Comment by Sornos** [comment]
Ahhh....My habit is to compile it directly on VRC and test it there.  With the update, I get similar behavior in VRC itself that it's not playable.

The update works perfectly fine in Unity and the starting pad shows up (Yeah, I didn't realize the play button was there.  Oops).

**Comment by mikeee324** [comment]
Glad the prefab thing is fixed!  
  
Now we just need to figure the other part out. It's odd that it works only in the editor though..  

When you press the E button to go into the desktop camera what exactly happens?  
Does it let you repeat the same thing more than once without rejoining/reloading the world?  

Do you use the Build & Test button to try it in VRC? (If so it should forward any error messages to the unity console window)  
If there's nothing showing there I think you can show the console in VRC with ```Right Shift + ` + 3``` ([VRC Docs](https://creators.vrchat.com/worlds/udon/debugging-udon-projects/#1-view-logs-in-vrchat))  
  
Are you using Unity 2022.3.22f1? (I only ever test on the latest stable of stuff and never any old stuff)  

Can you try recompiling all program sources? (`VRChat SDK -> Utilities -> Re-compile All Program Sources` - The menu at the top of your unity window)  
  
Failing that, have you tried a fresh project with the latest version to see if it starts behaving properly?

**Comment by Sornos** [comment]
I've been testing it, and apparently the glitch exists but is automatically corrected if I open and close the quick menu (ESC).  Then it plays normally.

Video of only the bug is here: https://youtu.be/4u2lXwDtGZI

Unity and VCC are current versions.  Also recompiled the sources and that quirk still exists.  When I look at the logs, I don't see anything out of the ordinary when the issue occurs or is corrected, I will need to read up on how to submit a log file.

**Comment by mikeee324** [comment]
Ahh.. interesting. It might be related to the bit of code that jumps out of that camera mode when the menu is opened.  
I wonder what it's detecting on your end that it doesn't on my machine.  
  
I'm currently working on a little persistence update so for now, so I'll add a toggle somewhere so you can disable that behaviour.

**Comment by Sornos** [comment]
Quickly pressing ESC twice to initialize is fine by me.  I'm used to enough workarounds (i.e. having to manually spin up the fans on my PCVR desktop using Command Prompt) that I'm kind of used to it.

Now that hole 1 works, I think I'll experiment around a bit.  Thanks for the help.

**Comment by mikeee324** [comment]
At least you can get to work now! I've made an attempt at fixing the issue anyway.  
I'm thinking it's related to having a personal mirror enabled. So it may or may not have fixed it.  
  
0.8.6 should be ready to grab soon! If you encounter issues you might have to start it from scratch again as I made quite a few changes and renamed a few bits. Unity doesn't like it sometimes.

**Comment by mikeee324** [comment]
Closing this now as I think you either got a workaround or it's hpefully just been fixed in the all the updates lately :)  
  
Lemme know if you have anything I can help with tho!  
Also let me know when you upload your world, I'd love to have a play on it sometime!
